# Generated by Django 2.0.1 on 2018-01-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80, unique=True)),
                ('specjalizacja', models.CharField(max_length=80)),
                ('staz', models.SmallIntegerField()),
                ('cena', models.FloatField()),
                ('pathToPicture', models.CharField(max_length=80)),
            ],
        ),
    ]
