# Generated by Django 2.0.1 on 2018-01-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_lekarz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='cena',
            field=models.SmallIntegerField(),
        ),
    ]
