# Generated by Django 2.0.1 on 2018-01-15 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180115_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lekarz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='imie',
        ),
        migrations.AddField(
            model_name='post',
            name='nazwisko',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='specjalizacja',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
