# Generated by Django 2.0.1 on 2018-01-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180115_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imie',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nazwisko',
        ),
        migrations.RemoveField(
            model_name='post',
            name='specjalizacja',
        ),
    ]
