# Generated by Django 2.0.1 on 2018-01-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180116_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekarz',
            name='cena',
            field=models.CharField(default=100, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lekarz',
            name='imię',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lekarz',
            name='nazwisko',
            field=models.CharField(max_length=20),
        ),
    ]
