# Generated by Django 2.0.1 on 2018-01-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180116_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='specjalizacja',
            field=models.CharField(choices=[('Chirurg', 'Chirurg'), ('Neurochirurg', 'Neurochirurg'), ('Kardiolog', 'Kardiolog'), ('Anestezjolog', 'Anestezjolog'), ('Endokrynolog', 'Endokrynolog')], default='Chirurg', max_length=20),
        ),
    ]
